CLIENT_SECRET = "YgA3ADAANgBjADkAZgAxAC0AYwBiAGMAOQAtADQAOAA5ADcALQA5ADMANABiAC0AMgBlAGYAZABmADYANQBjAGIAYgA2ADAA"
CLIENT_ID = "cfced01c-f520-4a32-acac-7c6d2e0da80c"
TENANT_ID = "d2e2d217-61ff-4ac2-98d9-2aedc90ac044"
UNIKEY_LOGIN_URL_BASE = "https://identity.unikey.com"
UNIKEY_API_URL_BASE = "https://resi-prd-api.unikey.com"
UNIKEY_WS_URL_BASE = "wss://resi-prd-ws.unikey.com"
UNIKEY_INVALID_LOGIN_URL = "https://identity.unikey.com/account/loginlocal"

LOCK_STATE_LOCK = 1
LOCK_STATE_UNLOCK = 2
LOCK_STATE_JAM = 8
LOCK_STATE_LOCK_JAM = 9
LOCK_STATE_UNLOCK_JAM = 10

COMMAND_STATUS_PROCESSING = 4
COMMAND_STATUS_DELIVERED = 7
COMMAND_STATUS_CANCELLED = 6
COMMAND_STATUS_COMPLETE = 5
